from models.job import Job
from models.metadata_package import MetadataPackage
from models.title_package import TitlePackage


class MetadataGenerator:
    def generate(self, job: Job, title_package: TitlePackage) -> MetadataPackage:
        description = f"{title_package.primary_title}\n\nAuto-generated by Zenith."

        hashtags = ["#gaming", "#viral", "#shorts"] if job.job_type.value == "gaming" else ["#trend", "#viral", "#shorts"]

        return MetadataPackage(
            job_id=job.job_id,
            description=description,
            hashtags=hashtags,
        )